### ISSUE TITLE
add next.js app to nx workspace

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#1]
## Description:
We need a UI

## Tasks:
- [x] add next.js app to nx workspace
- [x] add docs on how to start the application and view the ui

## Acceptance criteria:
- [x] npm run start will serve the ui

## Notes:

Read this: https://nx.dev/l/r/guides/nextjs about how to add nextjs apps to nx workspaces.
