### ISSUE TITLE
create a package that can deploy an upgradable contract

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#11]
## Description:
create a package that can deploy an upgradable contract

## Tasks:
- [x] Add tooling to be able to build contract
- [x] Inherit from libraries by openzepplin i.e. safe math
- [x] Write a basic contract

## Acceptance criteria:
- [x] be able to deploy the contract
- [x] be able to test the contract with remix
