### ISSUE TITLE
add config for starting `UI` inside openfin

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#3]
## Description:
add config for starting `UI` inside openfin

## Tasks:
- [ ] add schema/config inside `ui app`
- [ ] add run script to package.json to start openfin

## Acceptance criteria:
- [ ] when `npm run openfin` then openfin starts with the `UI`

## Notes:
Command isn't exactly like, is the config command
```sh
openfin --launch --url http://example.com
```

You'll need to find the config to go inside the next.js ui package.
