### ISSUE TITLE
restrict `C`reate, `U`pdate, `D`elete `productinventory` to manager

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#30]
## Description:
restrict `C`reate, `U`pdate, `D`elete `productinventory` to manager

## Tasks:
- [ ] restrict create, update, delete `productinventory` to manager
- [ ] make contract owner manager on constructor / initialisation

## Acceptance criteria:
- [ ] only warehouse manager and contract owner can update product inventory.
