### ISSUE TITLE
write IaC to deploy UI to k8 cluster

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#4]
## Description:
write IaC to deploy UI to k8 cluster

## Tasks:
- [ ] add some terraform
- [ ] add some github action

## Acceptance criteria:
- [ ] when command is ran then UI app is deployed to k8 cluster
- [ ] when workflow is triggered then UI is deployed to k8 cluster
- [ ] UI is reachable on k8 cluster

## Notes:

write some terraform
write a github action
hide some secrets
