### ISSUE TITLE
configure kubernetes cluster with terraform

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#7]
## Description:
configure kubernetes cluster with terraform

## Tasks:
- [x] setup vultr API key
- [x] set vultr_terraform provider
- [x] use vultr_kubernetes resource
- [x] add a test node to begin with
- [x] hide environment variables
- [x] add a command to trigger the apply
- [x] add deploy information to readme

## Acceptance criteria:
- [x] A command can ensure the k8 cluster is created, deleted, updated to match the expected state

## Notes:
https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/kubernetes
