### ISSUE TITLE
build a docker image publish to the registry

### ISSUE THREAD

**Issue by vince-lynch** [vince-lynch/playground-trading#9]
## Description:
build a docker image in gha and publish to the registry
We need docker images for the k8 pods to pull, 

## Tasks:
- [x] create a new PAT token
- [x] create a Dockerfile
- [x] create a docker-compose.yml
- [x] docker login can auth with registry
- [ ] image can publish from local
- [ ] create a GHA workflow

## Acceptance criteria:
- [x] image builds locally
- [x] image runs locally
- [x] image publishes from local
- [ ] When app / lib changes a new docker image should be published to the registry

## Notes:

Moving incomplete items to new issue as they separately concern the GHA workflow

**Comment by vince-lynch** [comment]
![fgrtttr](https://user-images.githubusercontent.com/16373282/141643946-b8547b71-1a3b-486e-80ee-6cc541e05aeb.PNG)
(have removed that PAT code so don't worry)

But yeah it has write permissions, so can't explain at the moment the issue with login

**Comment by vince-lynch** [comment]
Weird, nothing changed but is fine now.

![weird_is_fine_now](https://user-images.githubusercontent.com/16373282/141645399-e2a2213e-a336-4eff-b16a-d714c930d058.PNG)
